[supervisord]
nodaemon=true
user=root

[program:redis]
command=redis-server --appendonly yes --dir /data --bind 127.0.0.1
autostart=true
autorestart=true

[program:vod]
command=node index.js
directory=/app/vod
environment=REDIS_HOST="127.0.0.1",REDIS_PORT="6379",PORT="3000"
autostart=true
autorestart=true

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
